[git_branch]
symbol = "ğŸŒ¿ "

[git_metrics]
disabled = false

[os]
disabled = false
format = "$symbol "
symbols.Windows = "âŠ "

[username]
show_always = true

[hostname]
ssh_only = false

[shell]
disabled = false